// Generated by scripts/gen_contracts.py — do not edit by hand.
// Source: python/open_signal/*/models.py (spec §84–§157).

export interface SourceDefinition {
  id: string;
  name: string;
  category: "prediction_market" | "official_legal" | "official_government" | "scholarly_metadata" | "open_access_literature" | "clinical_registry" | "patent_data" | "news_metadata" | "other";
  authorityLevel: "primary_official" | "official_repository" | "licensed_aggregator" | "open_aggregator" | "secondary_source";
  accessMode: "rest" | "graphql" | "websocket" | "rss" | "atom" | "sparql" | "bulk_snapshot" | "file_download" | "web_fetch";
  baseUrl?: string | null;
  documentationUrl?: string | null;
  adapterId: string;
  rightsManifestId: string;
  updateCadence?: string | null;
  expectedLatency?: string | null;
  sourceStatus: "candidate" | "shadow" | "active" | "degraded" | "suspended" | "retired";
  healthCheckInterval: string;
  lastSuccessfulFetchAt?: string | null;
}


export interface RawSourceRecord {
  id: string;
  sourceId: string;
  externalId: string;
  externalParentId?: string | null;
  recordType: string;
  mimeType: string;
  payload: unknown;
  sourceCreatedAt?: string | null;
  sourceUpdatedAt?: string | null;
  firstSeenAt: string;
  lastSeenAt: string;
  ingestedAt: string;
  contentHash: string;
  transportMetadata?: Record<string, unknown>;
  rightsManifestId: string;
  adapterVersion: string;
  status: "active" | "changed" | "deleted" | "retracted" | "unavailable";
}


export interface CanonicalExpectation {
  id: string;
  canonicalQuestion: string;
  subjectEntityIds?: string[];
  eventType: string;
  outcomeType: "binary" | "categorical" | "threshold" | "range";
  threshold?: number | null;
  thresholdUnit?: string | null;
  observationStartAt?: string | null;
  resolutionDeadlineAt: string;
  resolutionAuthority?: string | null;
  resolutionRuleSummary: string;
  resolutionRuleHash: string;
  sourceMarketIds?: string[];
  status: "active" | "resolved" | "void" | "ambiguous" | "retired";
  canonicalizationVersion: string;
}


export interface MarketObservation {
  id: string;
  sourceMarketId: string;
  observedAt: string;
  probability?: number | null;
  bestBid?: number | null;
  bestAsk?: number | null;
  midpoint?: number | null;
  lastTradePrice?: number | null;
  spread?: number | null;
  volume?: number | null;
  openInterest?: number | null;
  priceMethod: "midpoint" | "last_trade" | "source_probability" | "unknown";
  dataQualityFlags?: string[];
  rawSourceRecordId?: string | null;
}


export interface CanonicalRule {
  id: string;
  title: string;
  jurisdictionId: string;
  issuingAuthorityId: string;
  ruleType: string;
  currentState: "announced" | "draft" | "consultation" | "committee_review" | "adopted" | "signed" | "effective" | "enforced" | "delayed" | "withdrawn" | "superseded";
  previousState?: "announced" | "draft" | "consultation" | "committee_review" | "adopted" | "signed" | "effective" | "enforced" | "delayed" | "withdrawn" | "superseded" | null;
  officialIdentifier?: string | null;
  docketIdentifiers?: string[];
  announcedAt?: string | null;
  adoptedAt?: string | null;
  signedAt?: string | null;
  effectiveAt?: string | null;
  enforcementAt?: string | null;
  delayedAt?: string | null;
  withdrawnAt?: string | null;
  supersededAt?: string | null;
  affectedEntityTypeIds?: string[];
  topicIds?: string[];
  currentVersionId: string;
  status: "active" | "withdrawn" | "superseded" | "expired";
  ontologyVersion: string;
}


export interface ResearchWork {
  id: string;
  title: string;
  publicationDate?: string | null;
  workType: "article" | "preprint" | "review" | "dataset" | "book" | "conference" | "other";
  doi?: string | null;
  externalIds?: Record<string, unknown>[];
  authorEntityIds?: string[];
  institutionEntityIds?: string[];
  topicIds?: string[];
  abstractText?: string | null;
  abstractRights?: string | null;
  openAccessLocations?: string[];
  sourceRecordIds?: string[];
  status: "active" | "retracted" | "corrected" | "merged";
}


export interface StructuredProposition {
  subjectIds?: string[];
  predicate: string;
  objectIds?: string[] | null;
  operator?: "equals" | "greater_than" | "less_than" | "increased" | "decreased" | "transitioned_to" | "will_occur" | "will_persist" | "is_forming" | "is_associated_with" | null;
  value?: number | null;
  unit?: string | null;
  baseline?: Record<string, unknown> | null;
  observationWindow?: Record<string, unknown> | null;
  qualifiers?: Record<string, unknown>;
  propositionVersion: string;
}
export interface Claim {
  id: string;
  institutionId: string;
  deskId: string;
  agentLineageId: string;
  modelVersion: string;
  charterVersion: string;
  runId: string;
  sectionId: string;
  capabilityId: string;
  claimType: "source_fact" | "derived_observation" | "attributed_interpretation" | "analytical_inference" | "editorial_judgment" | "forecast" | "structural_hypothesis";
  claimFamilyId?: string | null;
  publicStatement: string;
  structuredProposition: StructuredProposition;
  confidence?: number | null;
  confidenceLabel?: "low" | "medium" | "high" | "very_high" | null;
  epistemicStatus: "observed" | "derived" | "attributed" | "inferred" | "assessed" | "forecasted" | "hypothesized";
  evidenceBundleId: string;
  primaryEvidenceIds?: string[];
  counterEvidenceIds?: string[];
  alternativeExplanationIds?: string[];
  evidenceSnapshotHash: string;
  issuedAt: string;
  validFrom?: string | null;
  validUntil?: string | null;
  resolutionContractId?: string | null;
  status: "draft" | "verified" | "published" | "active" | "degraded" | "amended" | "withdrawn" | "expired" | "resolution_due" | "resolution_observed" | "resolved" | "ambiguous" | "unresolvable";
  currentVersionId: string;
  createdAt: string;
  updatedAt: string;
}


export interface RenderPlan {
  id: string;
  slotId: string;
  sectionInstanceId: string;
  claimIds?: string[];
  componentId: string;
  componentVersion: string;
  componentVariant: "compact" | "standard" | "lead" | "mobile";
  headline: string;
  dek?: string | null;
  displayFields?: Record<string, unknown>;
  hiddenDetailFields?: Record<string, unknown>;
  evidenceBundleId: string;
  visualPriority: number;
  mobilePriority: number;
  generatedBy: string;
  approvedByVerificationRunId: string;
}


export interface DailyEdition {
  id: string;
  editionDate: string;
  generatedAt: string;
  status: "draft" | "shadow" | "published" | "corrected" | "archived";
  leadRegion: RenderPlan;
  secondarySignals?: RenderPlan[];
  liveFeed: RenderPlan;
  digest: RenderPlan;
  mainContent?: RenderPlan[];
  utilityContent?: RenderPlan[];
  archivePreview: RenderPlan;
  includedSectionIds?: string[];
  includedClaimIds?: string[];
  composerVersion: string;
  componentVersions?: Record<string, unknown>;
  generationCostUsd: number;
  correctionCount?: number;
}

