"""Generate JSON Schema and TypeScript types from the Pydantic contracts.

Pipeline (spec §117.3): Pydantic Models -> JSON Schema -> TypeScript types.

Outputs:
  packages/contracts/schemas/<ModelName>.json   JSON Schema per model
  packages/contracts/src/types.ts               Generated TypeScript types
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from open_signal.canonical.models import (
    CanonicalExpectation,
    CanonicalRule,
    MarketObservation,
    ResearchWork,
)
from open_signal.claims.models import Claim
from open_signal.composer.models import DailyEdition, RenderPlan
from open_signal.sources.models import RawSourceRecord, SourceDefinition

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / "packages" / "contracts" / "schemas"
SRC_DIR = ROOT / "packages" / "contracts" / "src"

MODELS: list[tuple[str, type]] = [
    ("SourceDefinition", SourceDefinition),
    ("RawSourceRecord", RawSourceRecord),
    ("CanonicalExpectation", CanonicalExpectation),
    ("MarketObservation", MarketObservation),
    ("CanonicalRule", CanonicalRule),
    ("ResearchWork", ResearchWork),
    ("Claim", Claim),
    ("RenderPlan", RenderPlan),
    ("DailyEdition", DailyEdition),
]

TS_TYPE_MAP = {
    "string": "string",
    "number": "number",
    "integer": "number",
    "boolean": "boolean",
    "null": "null",
}

INDENT = "  "


def ts_type(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    """Convert a JSON Schema fragment to a TS type expression."""
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return ref
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    t = schema.get("type")
    if isinstance(t, list):
        t = " | ".join(TS_TYPE_MAP.get(x, "unknown") for x in t)
        return t
    if t == "array":
        items = schema.get("items", {})
        return f"{ts_type(items, defs)}[]"
    if t == "object":
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not props:
            return "Record<string, unknown>"
        lines = ["{"]
        for name, prop in props.items():
            opt = "" if name in required else "?"
            lines.append(f"{INDENT}{name}{opt}: {ts_type(prop, defs)};")
        lines.append("}")
        return "\n".join(lines)
    if t is None and "anyOf" in schema:
        return " | ".join(ts_type(s, defs) for s in schema["anyOf"])
    return TS_TYPE_MAP.get(t, "unknown")


def render_ts(name: str, schema: dict[str, Any], seen: set[str]) -> str:
    """Render one model as a TS interface, inlining $defs."""
    defs = schema.get("$defs", {})
    lines: list[str] = []

    # Emit $defs entries: enum -> type alias, object -> interface.
    for def_name, def_schema in defs.items():
        if def_name in seen:
            continue
        seen.add(def_name)
        if "enum" in def_schema:
            values = " | ".join(json.dumps(v) for v in def_schema["enum"])
            lines.append(f"export type {def_name} = {values};")
        elif def_schema.get("type") == "object":
            props = def_schema.get("properties", {})
            required = set(def_schema.get("required", []))
            lines.append(f"export interface {def_name} {{")
            for prop_name, prop in props.items():
                opt = "" if prop_name in required else "?"
                lines.append(f"{INDENT}{prop_name}{opt}: {ts_type(prop, defs)};")
            lines.append("}")

    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines.append(f"export interface {name} {{")
    for prop_name, prop in props.items():
        opt = "" if prop_name in required else "?"
        lines.append(f"{INDENT}{prop_name}{opt}: {ts_type(prop, defs)};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    SRC_DIR.mkdir(parents=True, exist_ok=True)

    ts_parts: list[str] = [
        "// Generated by scripts/gen_contracts.py — do not edit by hand.",
        "// Source: python/open_signal/*/models.py (spec §84–§157).",
        "",
    ]
    seen: set[str] = set()
    for name, model in MODELS:
        schema = model.model_json_schema()
        (SCHEMA_DIR / f"{name}.json").write_text(
            json.dumps(schema, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        ts_parts.append(render_ts(name, schema, seen))
        seen.add(name)
        ts_parts.append("")

    (SRC_DIR / "types.ts").write_text("\n".join(ts_parts), encoding="utf-8")
    print(f"Generated {len(MODELS)} schemas -> {SCHEMA_DIR}")
    print(f"Generated types -> {SRC_DIR / 'types.ts'}")


if __name__ == "__main__":
    main()
