/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 246248483e42f0cde234823418c1d925)
interface __BaseEnv_Env {
	OPEN_SIGNAL_DATABASE_URL: string;
	DEEPSEEK_API_KEY: string;
	OPEN_SIGNAL_R2_ENDPOINT_URL: string;
	OPEN_SIGNAL_R2_ACCESS_KEY_ID: string;
	OPEN_SIGNAL_R2_SECRET_ACCESS_KEY: string;
	OPEN_SIGNAL_R2_PUBLIC_BUCKET: string;
	OPEN_SIGNAL_REVALIDATE_URL: string;
	OPEN_SIGNAL_REVALIDATE_TOKEN: string;
	OPEN_SIGNAL_BATCH: DurableObjectNamespace<import("./src/index").OpenSignalBatch>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "OpenSignalBatch";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPEN_SIGNAL_DATABASE_URL" | "DEEPSEEK_API_KEY" | "OPEN_SIGNAL_R2_ENDPOINT_URL" | "OPEN_SIGNAL_R2_ACCESS_KEY_ID" | "OPEN_SIGNAL_R2_SECRET_ACCESS_KEY" | "OPEN_SIGNAL_R2_PUBLIC_BUCKET" | "OPEN_SIGNAL_REVALIDATE_URL" | "OPEN_SIGNAL_REVALIDATE_TOKEN">> {}
}
